/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UsfModal {
        "close": () => Promise<void>;
        "closed": boolean;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface UsfStickyHeader {
        "gluedActive": boolean;
        "gluedStart": boolean;
        "threshold": number;
    }
}
declare global {
    interface HTMLUsfModalElement extends Components.UsfModal, HTMLStencilElement {
    }
    var HTMLUsfModalElement: {
        prototype: HTMLUsfModalElement;
        new (): HTMLUsfModalElement;
    };
    interface HTMLUsfStickyHeaderElement extends Components.UsfStickyHeader, HTMLStencilElement {
    }
    var HTMLUsfStickyHeaderElement: {
        prototype: HTMLUsfStickyHeaderElement;
        new (): HTMLUsfStickyHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "usf-modal": HTMLUsfModalElement;
        "usf-sticky-header": HTMLUsfStickyHeaderElement;
    }
}
declare namespace LocalJSX {
    interface UsfModal {
        "closed"?: boolean;
        "opened"?: boolean;
    }
    interface UsfStickyHeader {
        "gluedActive"?: boolean;
        "gluedStart"?: boolean;
        "threshold"?: number;
    }
    interface IntrinsicElements {
        "usf-modal": UsfModal;
        "usf-sticky-header": UsfStickyHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "usf-modal": LocalJSX.UsfModal & JSXBase.HTMLAttributes<HTMLUsfModalElement>;
            "usf-sticky-header": LocalJSX.UsfStickyHeader & JSXBase.HTMLAttributes<HTMLUsfStickyHeaderElement>;
        }
    }
}
